remote: false

experienceLevel:
 internship: false
 entry: false
 associate: false
 mid-senior level: true
 director: true
 executive: true

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: true
 24 hours: true

positions:
  - Project Manager

locations:
  - Chicago, IL

distance: 100

companyBlacklist:
  - Ancestry
  - Google
  - Nvidia
  - Microsoft
  - Meta
  - Netflix

titleBlacklist: